version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
